version: "3.8"
name: vue-ci-cd   # 👈 nombre del proyecto

services:
  jenkins:
    build: ./jenkins   # carpeta donde está tu Dockerfile de Jenkins con Node.js
    container_name: jenkins-vue
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Conexión con agentes Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

  web1:
    build: ./servidor_nginx   # carpeta con el Dockerfile del servidor nginx+ssh
    container_name: vue-nginx-1
    ports:
      - "8081:80"   # Nginx
      - "2221:22"   # SSH
    volumes:
      - ./proyecto1:/var/www/html
    restart: unless-stopped

  web2:
    build: ./servidor_nginx
    container_name: vue-nginx-2
    ports:
      - "8082:80"
      - "2222:22"
    volumes:
      - ./proyecto2:/var/www/html
    restart: unless-stopped

volumes:
  jenkins_home:
